"""empty message

Revision ID: 282054f388eb
Revises: e11bad7f9717
Create Date: 2025-10-13 18:45:20.860190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282054f388eb'
down_revision = 'e11bad7f9717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites_characters')
    # ### end Alembic commands ###
