"""empty message

Revision ID: d40731afacd2
Revises: 4e9c13f5f3eb
Create Date: 2025-10-22 15:28:44.193855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40731afacd2'
down_revision = '4e9c13f5f3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_characters', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_favorite_character_per_user', ['user_id', 'character_id'])

    with op.batch_alter_table('favorites_planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_favorite_planet_per_user', ['user_id', 'planet_id'])

    with op.batch_alter_table('favorites_starships', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_favorite_starship_per_user', ['user_id', 'starship_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_starships', schema=None) as batch_op:
        batch_op.drop_constraint('unique_favorite_starship_per_user', type_='unique')

    with op.batch_alter_table('favorites_planets', schema=None) as batch_op:
        batch_op.drop_constraint('unique_favorite_planet_per_user', type_='unique')

    with op.batch_alter_table('favorites_characters', schema=None) as batch_op:
        batch_op.drop_constraint('unique_favorite_character_per_user', type_='unique')

    # ### end Alembic commands ###
