"""empty message

Revision ID: f155b2b4130f
Revises: d40731afacd2
Create Date: 2025-10-22 15:31:45.069460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f155b2b4130f'
down_revision = 'd40731afacd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_characters', schema=None) as batch_op:
        batch_op.drop_constraint('unique_favorite_character_per_user', type_='unique')

    with op.batch_alter_table('favorites_planets', schema=None) as batch_op:
        batch_op.drop_constraint('unique_favorite_planet_per_user', type_='unique')

    with op.batch_alter_table('favorites_starships', schema=None) as batch_op:
        batch_op.drop_constraint('unique_favorite_starship_per_user', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_starships', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_favorite_starship_per_user', ['user_id', 'starship_id'])

    with op.batch_alter_table('favorites_planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_favorite_planet_per_user', ['user_id', 'planet_id'])

    with op.batch_alter_table('favorites_characters', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_favorite_character_per_user', ['user_id', 'character_id'])

    # ### end Alembic commands ###
